[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["ws"] }
hyper = { version = "1.5.2", features = ["full"] }
tokio = { version = "1.43.0", features = ["full"]}
futures-util = "0.3.31"
serde_json = "1.0.135"
